export const FREE_DAILY_SCORE_LIMIT = 10;

export const HIGH_MATCH_SCORE_THRESHOLD = 80;

export const FREE_DAILY_CAREER_COACH_MESSAGE_LIMIT = 10;
export const PRO_DAILY_CAREER_COACH_MESSAGE_LIMIT = 30;
