// Manually maintained synonym → canonical slug map (roadmap.md §1.1: kept
// human-curated rather than learned at runtime, to avoid dirty data
// polluting the ranking). Only covers common variant spellings actually
// worth merging — an unmapped skill still works fine, it just won't be
// merged with any of its variants.
export const SKILL_SYNONYMS: Record<string, string> = {
  // Languages
  js: 'javascript',
  javascript: 'javascript',
  ts: 'typescript',
  typescript: 'typescript',
  py: 'python',
  python: 'python',
  golang: 'go',
  go: 'go',
  'c#': 'csharp',
  csharp: 'csharp',
  'c++': 'cpp',
  cpp: 'cpp',
  rb: 'ruby',
  ruby: 'ruby',
  rust: 'rust',
  kotlin: 'kotlin',
  swift: 'swift',
  php: 'php',
  java: 'java',
  scala: 'scala',
  elixir: 'elixir',

  // Runtimes / backend frameworks
  node: 'node.js',
  nodejs: 'node.js',
  'node.js': 'node.js',
  express: 'express',
  expressjs: 'express',
  nestjs: 'nestjs',
  nest: 'nestjs',
  django: 'django',
  flask: 'flask',
  fastapi: 'fastapi',
  rails: 'rails',
  'ruby on rails': 'rails',
  spring: 'spring',
  'spring boot': 'spring',
  laravel: 'laravel',

  // Frontend
  react: 'react',
  reactjs: 'react',
  'react.js': 'react',
  vue: 'vue',
  vuejs: 'vue',
  'vue.js': 'vue',
  angular: 'angular',
  angularjs: 'angular',
  svelte: 'svelte',
  nextjs: 'next.js',
  'next.js': 'next.js',
  nuxt: 'nuxt',
  'nuxt.js': 'nuxt',
  fullstack: 'full-stack',
  'full stack': 'full-stack',
  'full-stack': 'full-stack',

  // Databases
  postgres: 'postgresql',
  postgresql: 'postgresql',
  psql: 'postgresql',
  mysql: 'mysql',
  mongo: 'mongodb',
  mongodb: 'mongodb',
  redis: 'redis',
  sqlite: 'sqlite',
  dynamodb: 'dynamodb',
  cassandra: 'cassandra',
  elasticsearch: 'elasticsearch',

  // Cloud / DevOps
  k8s: 'kubernetes',
  kubernetes: 'kubernetes',
  docker: 'docker',
  aws: 'aws',
  gcp: 'gcp',
  'google cloud': 'gcp',
  azure: 'azure',
  terraform: 'terraform',
  ansible: 'ansible',
  'ci/cd': 'ci-cd',
  cicd: 'ci-cd',
  devops: 'devops',
  sre: 'sre',

  // AI/ML
  ml: 'machine-learning',
  'machine learning': 'machine-learning',
  ai: 'artificial-intelligence',
  llm: 'llm',
  llms: 'llm',
  'large language models': 'llm',
  pytorch: 'pytorch',
  tensorflow: 'tensorflow',
  nlp: 'nlp',

  // API / architecture
  graphql: 'graphql',
  rest: 'rest-api',
  'rest api': 'rest-api',
  restapi: 'rest-api',
  microservices: 'microservices',
  grpc: 'grpc',
};
